# Generated by Django 5.2.6 on 2025-09-08 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=100, verbose_name='Nome do serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tratamento', models.CharField(max_length=100, verbose_name='Nome do tratamento')),
                ('tipo_tratamento', models.CharField(default='teste', max_length=50, verbose_name='Tipo de Tratamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(max_length=100, verbose_name='Nome da vacina')),
                ('tipo_vacina', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('crmv', models.CharField(max_length=20, unique=True, verbose_name='CRMV')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do animal')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('porte', models.CharField(max_length=30, verbose_name='Porte')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente', verbose_name='Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data')),
                ('hora_agendamento', models.TimeField(verbose_name='Hora')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.animal', verbose_name='Animal')),
                ('id_servicos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicos', verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='RealizacaoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField(verbose_name='Data de realização')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.animal', verbose_name='Animal')),
                ('id_tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.tratamento', verbose_name='Tratamento')),
                ('id_veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.veterinario', verbose_name='Veterinário')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(verbose_name='Data da consulta')),
                ('hora_consulta', models.TimeField(verbose_name='Hora da consulta')),
                ('descricao', models.TextField(verbose_name='Descrição do atendimento')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.animal', verbose_name='Animal')),
                ('id_veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.veterinario', verbose_name='Veterinário')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacaoVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(verbose_name='Data de aplicação')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.animal', verbose_name='Animal')),
                ('id_vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.vacina', verbose_name='Vacina')),
                ('id_veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.veterinario', verbose_name='Veterinário')),
            ],
        ),
    ]
