# Generated by Django 5.2.4 on 2025-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='tipo_tratamento',
            field=models.CharField(default='teste', max_length=50, verbose_name='Tipo de Tratamento'),
        ),
    ]
