# Generated by Django 5.2.6 on 2025-09-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='duracao_minutos',
            field=models.IntegerField(default=60, verbose_name='Duração em minutos'),
        ),
    ]
